### ISSUE TITLE
Picture attribute does not work

### ISSUE THREAD

**Issue by Somfic** [AlexanderWillner/kingraph#3]
I can't use the picture attribute.

YAML:
```yml
families:
  - house: Dyer
    families:
    - parents: [Edward, Sammy]

people:
  Edward:
    picture: edward1.PNG
``` 

Output:
```
> kingraph fam.yaml > fam.svg

Error: in label of node Edward

    at render (C:\Users\%username%\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:94:11)
    at Viz (C:\Users\%username%\AppData\Roaming\npm\node_modules\kingraph\node_modules\viz.js\viz.js:75:12)
    at render (C:\Users\%username%\AppData\Roaming\npm\node_modules\kingraph\lib\render.js:23:32)
    at render (C:\Users\%username%\AppData\Roaming\npm\node_modules\kingraph\lib\render.js:15:28)
    at C:\Users\%username%\AppData\Roaming\npm\node_modules\kingraph\bin\kingraph:27:12
    at Array.map (<anonymous>)
    at C:\Users\%username%\AppData\Roaming\npm\node_modules\kingraph\bin\kingraph:23:24
``` 

I'm using `v0.2.0`.
